//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeAddvisor.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cliente
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Servicio = new HashSet<Servicio>();
        }

        public int Id_Cliente { get; set; }
        [MinLength(12, ErrorMessage = "{0} el largo debe ser de 12")]
        [Display(Name = "Ingrese su rut de Cliente :)")]
        public string Rut_Cliente { get; set; }

        public string Nombre_Cliente { get; set; }
        public string ApellidoPa_Cliente { get; set; }
        public string ApellidoMa_Cliente { get; set; }
        public string Domicilio_Cliente { get; set; }
        public Nullable<bool> Bloqueado { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> Id_Comuna { get; set; }
        public Nullable<int> Id_Region { get; set; }
    
        public virtual Comuna Comuna { get; set; }
        public virtual Region Region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicio> Servicio { get; set; }
    }
}
