//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeAddvisor.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deuda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deuda()
        {
            this.Servicio1 = new HashSet<Servicio>();
        }
    
        public int Id_Deuda { get; set; }
        public Nullable<int> Id_Servicio { get; set; }
        public string Monto_Deuda { get; set; }
        public string Porcentaje_Deuda { get; set; }
    
        public virtual Servicio Servicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicio> Servicio1 { get; set; }
    }
}
