//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeAddvisor.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesional
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profesional()
        {
            this.Servicio = new HashSet<Servicio>();
        }
    
        public int Id_Profesional { get; set; }
        public string Rut_Profesional { get; set; }
        public string Nombre_Profesional { get; set; }
        public string ApellidoPa_Profesional { get; set; }
        public string ApellidoMa_Profesional { get; set; }
        public string Domicilio_Profesional { get; set; }
        public Nullable<bool> Bloqueado { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Telefono { get; set; }
        public Nullable<bool> Capacitacion { get; set; }
        public byte[] Imagen { get; set; }
        public string Disponibilidad { get; set; }
        public string Jornada { get; set; }
        public Nullable<int> Codigo_Profesional { get; set; }
        public Nullable<int> Id_RegionP { get; set; }
        public Nullable<int> Id_ComunaP { get; set; }
    
        public virtual Comuna Comuna { get; set; }
        public virtual Tipo_Profesional Tipo_Profesional { get; set; }
        public virtual Region Region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicio> Servicio { get; set; }
    }
}
