//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeAddvisor.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servicio()
        {
            this.Deuda = new HashSet<Deuda>();
        }
    
        public int Id_Servicio { get; set; }
        public Nullable<int> Id_Cliente { get; set; }
        public Nullable<int> Id_Profesional { get; set; }
        public Nullable<int> Id_Deuda { get; set; }
        public string Descripcion_Servicio { get; set; }
        public Nullable<int> Total_Servicio { get; set; }
        public Nullable<System.DateTime> Fecha_Servicio { get; set; }
        public string Direccion { get; set; }
        public string Clasificacion { get; set; }
        public Nullable<int> Id_ComunaS { get; set; }
        public Nullable<int> Id_RegionS { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Comuna Comuna { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deuda> Deuda { get; set; }
        public virtual Deuda Deuda1 { get; set; }
        public virtual Profesional Profesional { get; set; }
        public virtual Region Region { get; set; }
    }
}
